do less 'make check' local test install hacks -> do 'make installcheck' instead
git-svn-id: https://svn.code.sf.net/p/gphoto/code/trunk/libgphoto2@9187 67ed7778-7388-44ab-90cf-0a291f65f57c

diff --git a/tests/Makefile.am b/tests/Makefile.am
--- a/tests/Makefile.am
+++ b/tests/Makefile.am
@@ -8,7 +8,30 @@ check_SCRIPTS = \
 EXTRA_DIST = \
 	check-camera-list.in
 
-TESTS = $(check_SCRIPTS)
+# TESTS = $(check_SCRIPTS)
+
+# FIXME: Only run this if not cross-compiling
+installcheck-local: test-camera-list
+	@export CAMLIBS="$(DESTDIR)$(camlibdir)"; \
+	total=0; failed=0; success=0; \
+	echo "Running \"installcheck\" test cases..."; \
+	for script in test-camera-list; do \
+		echo "Test case: $$script"; \
+		total="$$(expr $$total + 1)"; \
+		if "./$$script"; then \
+			echo "SUCCEEDED: $$script"; \
+			success="$$(expr $$success + 1)"; \
+		else \
+			s="$$?"; \
+			echo "FAILED (return code $$s): $$script"; \
+			failed="$$(expr $$failed + 1)"; \
+		fi; \
+	done; \
+	echo "Test summary: $$success succeeded, $$failed failed, $$total in total."; \
+	if test "$$failed" -gt 0; then \
+		echo "Error: One or more \"installcheck\" testcases have failed."; \
+		exit 1; \
+	fi
 
 CLEANFILES = $(check_SCRIPTS)
 
